// Flappy Bird
const canvas=document.getElementById('gameCanvas');
const ctx=canvas.getContext('2d');
function resize(){canvas.width=window.innerWidth;canvas.height=window.innerHeight;}
window.addEventListener('resize',resize);resize();
const settings={gravity:0.6,lift:-12,pipeSpeed:20,pipeWidth:50,minGap:200,maxGap:350,pipeDist:300};
const bird={x:100,y:canvas.height/2,w:40,h:30,vel:0,gravity:settings.gravity,lift:settings.lift};
let pipes=[],score=0,gameOver=false;
function reset(){bird.y=canvas.height/2;bird.vel=0;pipes=[];score=0;gameOver=false;spawnPipe();}
function spawnPipe(){const pipeGap=Math.random()*(settings.maxGap-settings.minGap)+settings.minGap;const topH=Math.random()*(canvas.height-pipeGap-200)+100;const bottomY=topH+pipeGap;pipes.push({x:canvas.width,y:0,w:settings.pipeWidth,h:topH});pipes.push({x:canvas.width,y:bottomY,w:settings.pipeWidth,h:canvas.height-bottomY});}
function update(){if(gameOver)return;bird.vel+=bird.gravity;bird.y+=bird.vel;pipes.forEach(p=>p.x-=settings.pipeSpeed);if(pipes.length===0||canvas.width-pipes[pipes.length-1].x>=settings.pipeDist)spawnPipe();if(pipes.length&&pipes[0].x<-settings.pipeWidth){pipes.splice(0,2);score++;}for(const p of pipes){if(bird.x<p.x+p.w&&bird.x+bird.w>p.x&&bird.y<p.y+p.h&&bird.y+bird.h>p.y){gameOver=true;break;}}if(bird.y<0||bird.y+bird.h>canvas.height)gameOver=true;}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#ff0';ctx.fillRect(bird.x,bird.y,bird.w,bird.h);ctx.fillStyle='#0f0';pipes.forEach(p=>ctx.fillRect(p.x,p.y,p.w,p.h));ctx.fillStyle='#000';ctx.font='24px Arial';ctx.fillText('Score: '+score,20,40);if(gameOver){ctx.fillStyle='#f00';ctx.fillText('Game Over',canvas.width/2-80,canvas.height/2);}}
function createUI(){const c=document.createElement('div');c.style.position='fixed';c.style.top='10px';c.style.left='10px';c.style.background='rgba(255,255,255,0.9)';c.style.padding='10px';c.style.borderRadius='4px';c.style.fontFamily='sans-serif';c.style.boxShadow='0 2px 6px rgba(0,0,0,0.2)';const t=document.createElement('div');t.textContent='Game Settings';t.style.fontWeight='bold';t.style.marginBottom='8px';c.appendChild(t);const params=[{label:'Gravity',key:'gravity',min:0,max:5,step:0.1,value:settings.gravity},{label:'Lift',key:'lift',min:-20,max:0,step:1,value:settings.lift},{label:'Pipe Speed',key:'pipeSpeed',min:5,max:50,step:1,value:settings.pipeSpeed},{label:'Pipe Width',key:'pipeWidth',min:10,max:100,step:5,value:settings.pipeWidth},{label:'Min Gap',key:'minGap',min:100,max:400,step:10,value:settings.minGap},{label:'Max Gap',key:'maxGap',min:200,max:500,step:10,value:settings.maxGap},{label:'Pipe Dist',key:'pipeDist',min:200,max:600,step:20,value:settings.pipeDist}];params.forEach(p=>{const w=document.createElement('div');w.style.marginBottom='6px';const l=document.createElement('div');l.textContent=p.label+':';const s=document.createElement('input');s.type='range';s.min=p.min;s.max=p.max;s.step=p.step;s.value=p.value;const v=document.createElement('span');v.textContent=p.value;v.style.marginLeft='8px';l.appendChild(s);l.appendChild(v);w.appendChild(l);c.appendChild(w);s.addEventListener('input',()=>{const val=parseFloat(s.value);settings[p.key]=val;v.textContent=val;if(p.key==='gravity')bird.gravity=val;if(p.key==='lift')bird.lift=val;});});document.body.appendChild(c);}createUI();
window.addEventListener('keydown',e=>{if(e.code==='Space'){if(gameOver)reset();else bird.vel=settings.lift;}else if(gameOver&&e.key.toLowerCase()==='r')reset();});
function loop(){update();draw();requestAnimationFrame(loop);}loop();
